#ifndef HAL_ADDRESSES_H
#define HAL_ADDRESSES_H

#include "xparameters.h"

#define APP_GPIOA_BASE       XPAR_GPIO_0_S00_AXI_BASEADDR
#define APP_GPIOB_BASE       XPAR_GPIO_1_S00_AXI_BASEADDR
#define APP_GPIOC_BASE       XPAR_GPIO_2_S00_AXI_BASEADDR
#define APP_GPIOD_BASE       XPAR_GPIO_3_S00_AXI_BASEADDR

#define APP_I2C_LCD_BASE     XPAR_I2C_LCD_AXI_0_S00_AXI_BASEADDR
#define APP_CUSTOM_UART_BASE XPAR_UART_0_S00_AXI_BASEADDR
#define APP_UARTLITE_BASE    XPAR_AXI_UARTLITE_0_BASEADDR

#ifdef XPAR_SPI_0_S00_AXI_BASEADDR
#define APP_HAS_SPI          1
#define APP_SPI_BASE         XPAR_SPI_0_S00_AXI_BASEADDR
#else
#define APP_HAS_SPI          0
#endif

#endif
